language: node_js
node_js:
- '6'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-lts-2.16
  - EMBER_TRY_SCENARIO=ember-lts-2.18
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default
  global:
    # See https://git.io/vdao3 for details.
    JOBS: 1
    secure: fOTO/HpUT0xsfml9iXuEL9qBu0NVErcig6CmrS1DFv7f4x9/mYQMNzLUv5b6VBPqGHeFNHiGaUUza3Ufc5KpL7DOu/1y6TFQlSoM6MRRdIXb+50MObvkJ4wXwYJH7Zrb4g8RTaBOY9uU5XQkm/E6GWWF3NiYFoVzCYPNSgAALko1caoEX2hoJNXJSd0T4G+gxtxc2g08RGunBPLqIyy2avMRN4yq0WDN2NbBrztM01FA5RoOLPyX0hhzyIZ+45z34wKvZtu7rj9h1KbFOZOVFJWpHDa0bXxhF63ldxPINe2QMOSsOD22Czk1+IKyC+88gtkvUq7pGUaJK6YdVDRcW9G/DMHVy/IE2aFabrPDVgzrmeCoVKzATzt8nMfIMTTu9Unoa5fdohpJ0NPhYnPfVAGfJ+2MPITgP+x2X6M5+KgHCBdaIgwBVnZE9DTb1L9c/Eh50zeHHbfv9L+NVlbQFzMWNj+kKWMj0qwh6JPpSFiKaOvTK6XP+NSUc7euAZgqK6lwqS07pvcql4qvzbeRWyn/GZuRHOGvfkUNuvLee8dMKfpF3s1VQ6blHHqKB8qH2ifxawiztWgUkYxK0GFTk//ZopLzP90bLl0JiGlg517tp5V9eBOK5ZlPwsSOhD+wta9gCssPjK4i2H2IwLox7AqXegigBMdqIbXz9LaFVAY=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add greenkeeper-lockfile@1
- yarn global add codecov
install:
- yarn install --no-lockfile --non-interactive
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint:js
- COVERAGE=true node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
- codecov
notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    rooms:
      secure: ro4pknbvHJV05FXHSD0XDgoq/Z5nHGkdifQYZkx1UOD4y4zw3yLorHWUVyQx8jhhgNxx+Gzl2t7qb7IUSRzQt3UWeqYHmMiH8pcyUMbbYFO8UqmwqVQBUQnPhhNW7D+MZYMp9gJGLoHu5uSrzLxkNuDiMZujoecEPPe8jhble0iMqJnn+X/tkIrlCNq7bs6cLPikgFrsU8fBa5rFk/4YfnANkaa1eRYBK091fjM5SPIUFrGXFvQ5pJAJPmz1jlWEQxiefSzYtEBFhtJNXqi7vjFrZxF4CXN+TOAfITfMxo3MFxoeFwcmMYe6T7lRQDd0yMeUHonCV6mnu/rtEBinticmOL9XW7ol2CQEzt9mPWwSeGIU0Nj7MzU7pqQyoFi1+3DQFaiOkr+q53uheDYRMO0H+PdjJeSpnznSOhuetscEAE9WHAXLK9NEl7mQ+sDf707Pd9ORnrmdzShnm9gwrlfbtDHi9uRRUruyTPiJMLfNdHzA4ShuAV17B2W948oAH+QA5rX++9Qd2Cw8UquJjXBXkfFY0rEzt2ZthSS7i+locFwQI63uV/f2rBKS8xu1xr71BXQUHumgg51+JKvkxyxiGpPpXaYn9tChGk5NdRCpv/MKO56yeUMfUboLyaGNuW3jX0NN4k2Bu/4JVca8Cx3cD1AORc9ZPwDGNPJ2Mj8=
